sentry:
    build: .
    command: start
    ports:
        - "9000"
    volumes:
        - ./sentry_data:/data
    environment:
        SECRET_KEY: randomvalue
        SENTRY_URL_PREFIX: http://sentry.ipython.com
        VIRTUAL_HOST: sentry.ipython.com
        VIRTUAL_PORT: 9000

