notebook:
    build: .
    #command: python /usr/local/bin/ipython notebook --no-browser --port 8888 --debug --ip=0.0.0.0 --notebook-dir=/notebook-dir
    ports:
        - "8888"
    volumes:
        - .:/notebook-dir/shared
